#spring配置
spring:
  #缓存服务器配置
  cache:
    type: redis

  redis:
    database: 1
    host: localhost
    pool:
      max-active: 20
    password: '{cipher}AQCwyCY8OUjnCS0t4dHw9hhI43CRL6IPK4I1hOP2vV+RJoGoNTyefyXV244Qr3W8zYUuxeLYjRVZphZ/5td6vj/Pc3qF/DoK4dGW2FojPerxRYPb7g/9+zQCu7kBVwqbWLACKFJrI12UToYEWXOROg2yi6Yttn898oEqZYoySy3q0t2qnP21UpNhTyIbJ52V5374t/NTc3d57ERM1zeZckVzSTC8JP6zK/0vJ3kvSTk9cbgZi8dqQ/ErkMBQxmBcMKw8CDIt9f7h2GP/SiqwL13PYEsBTcQNEJzaer6H5vxgJalZY2BU5SegUzIMCgP6pQGwqIN/qGTRLTsEKU6Xp0YfVcdwEmYP5wRLljkGw6p+u67yGYHo7tp6CgFVCTrhiT8='
    #消息中间件配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#模版缓存配置
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html
#API网关配置
zuul:
  #路由配置
  routes:
      sso: #登录认证服务
        #响应的路径
        path: /pay/**
        #敏感头信息
        sensitiveHeaders:
        #重定向到的服务（根据服务id名称从注册中心获取服务地址）
        serviceId:  kbj-pay
      producer: #生产者服务
        #响应的路径
        path: /management/**
        sensitiveHeaders:
        #重定向到的服务（根据服务id名称从注册中心获取服务地址）
        serviceId:  kbj-management
    #添加代理头
  add-proxy-headers: true

#日志设置
logging:
  level:
    org.springframework: error
    org.hibernate: info
    com.kbj.kbj_gateway.sso: debug
#发送邮件配置
custom:
  mailConfig:
    #服务器
    mailHost: smtp.qq.com
    #端口号
    mailPort: 587
    #邮箱账号
    mailUsername: 1289251150@qq.com
    #邮箱授权码
    mailPassword: '{cipher}AQCYe6J4xZ0gaCsQvv1ESlGHfQnE6/ERPV+ZtCKohEJX0yE6ohT1E5c9swa/ScfTk5Sh9opLqpPpZw8ZEvduHVvUiWBxvwcReoQh6fdOV/aIgcbTNpU75+kb0ZX8igfAxHf42PFxSyXMlGU2zUETiNnOy1ul6e0rO/6wFbxLh7zw6nlzgiPv0QiYYgN7rG8tRGL0l3oVVTsLusdSLo9y+sDrrW8tlv6jCWP8ys2GySfN0YaKfP27AECezhgzXc9Zx/+1p61aNPmJFC/qYrzCNV9AdesO33yhoMqJ34fRtHn57cbz6oBFkJL1eP8SzPj+PIUD7nKhm9PKkDwuBor7maVgH2q9wMAbQ7LU6WUxRpC1G9Sf69w3xTX0UtQ4gM9crVR/jDKdSKfS7Od+cjl53Ue5'
    #时间延迟
    mailTimeout: 25000
    #发送人
    mailFrom: 1289251150@qq.com
    #发件人名字
    mailPersonal: 阿拉斯加他哥
#  83551a3cb81b13eb8436f99a90823898
#解决GET请求变成POST请求
feign:
  httpclient:
    enabled: true
#解决无法调用fallback
  hystrix:
    enabled: true
