#spring配置
spring:
  #缓存服务器配置
  cache:
    type: redis

  redis:
    database: 1
    host: 192.168.2.118
    pool:
      max-active: 20
    password: '{cipher}AQAUKgCbb/S1RNOEfR1f0R5uTkAIrSEvFwb+70NCVp4TSnE1I83faWNeTcD5IWFosGYVnHndftZEDm31G4H0TIT8RUSLYBqvY/PUcRs13auVqfG6zDJGYcHA+3Oqd2OOWB9Jhbt1kixsN2WFwi9FzYXz37QEKxn3WMjDIr3x8lL8b4+aB0pxwOTT2RKX/M26czAEnJprRXAmfEXL+/hA8vQwHBk2gtblq2DB3fg3ImGcpbCUCQSznaYsDhYQUlMierOh1Edg+2WqjFGhuJfFfZs/yu8dF7Dsma0eM1tTpKv1dQnfs1G0UEzI2lqZ8vNy5sCzeEfL/LtUaC9jDA69orc7K3QnGNEa+0S4yFI/l98ZVgVZD55fXhvo9FMa+iNVhtQ='
    #消息中间件配置
  rabbitmq:
    host: 192.168.2.118
    port: 5672
    username: guest
    password: guest
#模版缓存配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mvc:
    view:
      suffix: .html
#API网关配置
zuul:
  #路由配置
  routes:
      sso: #登录认证服务
        #响应的路径
        path: /pay/**
        #敏感头信息
        sensitiveHeaders:
        #重定向到的服务（根据服务id名称从注册中心获取服务地址）
        serviceId:  kbj-pay
      producer: #生产者服务
        #响应的路径
        path: /manage/**
        sensitiveHeaders:
        #重定向到的服务（根据服务id名称从注册中心获取服务地址）
        serviceId:  kbj-manage
    #添加代理头
  add-proxy-headers: true
  host: 
     connect-timeout-millis: 10000
     socket-timeout-millis: 60000

#日志设置
logging:
  level:
    org.springframework: info
    org.hibernate: info
    com.kbj.kbj_gateway.sso: debug

#  83551a3cb81b13eb8436f99a90823898
#解决GET请求变成POST请求
feign:
  httpclient:
    enabled: true
#解决无法调用fallback
  hystrix:
    enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
